### ISSUE TITLE
Hide sort button when there's only table headers/no table content

### ISSUE THREAD

**Issue by nucspl** [alexandru-dinu/obsidian-sortable#32]
It's just a small visual issue I encounter when using tables like this...
![image](https://user-images.githubusercontent.com/80261260/182036039-b90851eb-a652-48eb-85a6-976b5abb5ec5.png)

**Comment by alexandru-dinu** [comment]
I decided to remove the "up-down" arrows for **all** tables. This is the easiest the cleanest solution.

So now, all tables, in their default state, have the headers unchanged (by CSS). The cycle is like this:
- 1st click on a header: the up arrow appears (due to sorting in ascending order).
- 2nd click on a header: the down arrow appears (due to sorting in descending order).
- 3rd click: reset to default state, no up-down arrows.

**Comment by alexandru-dinu** [comment]
Done in https://github.com/alexandru-dinu/obsidian-sortable/releases/tag/0.2.6.

**Comment by nucspl** [comment]
I like this implementation, clean and simple!
